language: csharp

install:
  - sudo apt-get install -y libglib2.0-cil-dev libgtk2.0-cil-dev libglade2.0-cil-dev
  - sudo apt-get install -y liblog4net-cil-dev libpcsclite-dev

mono:
  - latest
  - 3.12.0

script:    # build gtk gui
  - ./build-linux/build-lnx-monosim-gtk-full.sh
